[general]
interval=15
jbenable=yes

[quectel0]
data=/dev/dji-modem-at
uac=on
alsadev=hw:Android
context=cellular-incoming
group=0
msg_direct=on
msg_storage=me
autodeletesms=yes
resetquectel=no
qhup=on

